/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_example_NativeUtil */

#ifndef _Included_com_jni_example_NativeUtil
#define _Included_com_jni_example_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_example_NativeUtil
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_example_NativeUtil_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
