/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_example_NativeUtils */
#ifndef _Included_com_jni_example_NativeUtils
#define _Included_com_jni_example_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_example_NativeUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_example_NativeUtils_getStringFromNative
  (JNIEnv *env, jclass jobj){
      return (*env)->NewStringUTF(env,"Hello From JNI!");}

#ifdef __cplusplus
}
#endif
#endif